### ISSUE TITLE
Not able to get it to work

### ISSUE THREAD

**Issue by madmessmoving** [raaftech/logelastic#2]
Hello,

I'm new to java, Mulesoft and Elastic and trying to use this to post logs from MS to elastic. I followed your instructions about adding the dependency to POM and the log4j configuration. I don't see any error on Anypoint Studio console but I'm also not seeing any logs on kibana. Here is my log4J2.xml:

<?xml version="1.0" encoding="utf-8"?>
<Configuration packages="com.ahold.development.logging.log4j.appender">

    

    <Appenders>
    		
    		<Console name="console" target="SYSTEM_OUT">
            <PatternLayout pattern="[%level] [%d] [${hostName}] %c{1}: %msg%n" />
        </Console>
       

    <Elastic name="elastic" url="http://localhost:9200">
            <Property name="X-Java-Runtime" value="$${java:runtime}" />
            <JsonLayout complete="false" properties="true"/>
        </Elastic>
        
        
    </Appenders>
    <Loggers>
        
        
        
        
         
		        
        

        <AsyncRoot level="INFO">
            
            <AppenderRef ref="console" />
            <AppenderRef ref="elastic" />
        </AsyncRoot>
    </Loggers>
</Configuration>

Could you please suggest what I might be missing. Sorry if this is not the correct medium to ask and I might be missing something obvious as I'm not experience with java. I'm working with Mule Runtime 4.2

**Comment by rubin55** [comment]
Hi :). You need to copy the logelastic.jar to the lib/boot directory of the embedded mule runtime; it should be somewhere in the plugins folder of Anypoint Studio. When I get home I’ll double check the folder location.

**Comment by madmessmoving** [comment]
Hi, Thanks for the quick reply.

I think I found the plugins folder '/Applications/AnypointStudio.app/Contents/Eclipse/plugins' (I'm on mac and new to this also) but I'm not seeing logelastic.jar. See a bunch of org.*.jar's. But I think I can download the jar from maven: https://mvnrepository.com/artifact/tech.raaf/logelastic/2.8.2. If could pls suggest where to drop it? Also we're in cloudhub so can we put somewhere in runtime on cloud? Thanks again for the prompt reply.

**Comment by rubin55** [comment]
Hey, 

So when you can install multiple runtimes in Anypoint Studio. By default you'll have one runtime installed, but through the update and install functions you can add more runtimes if you want. In my case, I have 4 runtimes installed. Take a look at this:

```
[rubin@kuro ~]$ find /Applications/Anypoint\ Studio\ 7.app/ -type d -name boot
/Applications/Anypoint Studio 7.app//Contents/Eclipse/configuration/org.eclipse.osgi/508/data/.runtimes/tooling-96jmyqxq/lib/boot
/Applications/Anypoint Studio 7.app//Contents/Eclipse/plugins/org.mule.tooling.server.4.2.1.ee_7.3.3.201908272106/mule/lib/boot
/Applications/Anypoint Studio 7.app//Contents/Eclipse/plugins/org.mule.tooling.server.4.2.2.ee_7.3.5.201911122027/mule/lib/boot
/Applications/Anypoint Studio 7.app//Contents/Eclipse/plugins/org.mule.tooling.server.4.1.2.ee_7.1.3.201908272106/mule/lib/boot
/Applications/Anypoint Studio 7.app//Contents/Eclipse/plugins/org.mule.tooling.server.4.1.5.ee_7.3.1.201908272106/mule/lib/boot
```
I said 4 runtimes, but you see 5 lines, what gives? That first one is the tooling runtime used for the DataSense functionality in Anypoint studio. What you want to do is place `logelastic-3.0.0.jar` in those boot directories. Optionally, you can then also edit the 'conf/log4j2.xml' file there, which will make the runtime itself also log to Elasticsearch. If you only edit the log4j2.xml (or log4j2.properties) in your project, then that will work also, you just won't see messages from the runtime itself, only from your own Mule application.

You can download the latest version of logelastic (3.0.0) [here](https://search.maven.org/artifact/tech.raaf/logelastic/3.0.0/jar). Click on the `Download` button in the top-right corner of the screen there, and select `jar`. After you've downloaded the jar, place it in the `lib/boot` directory of your embedded runtime. For example, if you have Anypoint Studio 7.4.0, with Mule Runtime 4.2.2, it will be something like:

`/Applications/Anypoint Studio 7.app//Contents/Eclipse/plugins/org.mule.tooling.server.4.2.2.ee_7.3.5.201911122027/mule/lib/boot`

On Windows the directory will be very similar, just have a look!

**Comment by rubin55** [comment]
Finally, some extra tips. Think about placing a log4j2.component.properties file in your resources directory (i.e, where your log4j2.xml or log4j2.properties file lives) to set a more resilient async queue policy. Example contents:

```
log4j2.asyncQueueFullPolicy=Discard
log4j2.discardThreshold=INFO
```

Long story short: if your Elasticsearch instance is slow to respond (busy, many messages, etc) your Log4j2 buffer within your application can become full. Log4j2 will by default then switch from async to sync mode, to try and get rid of the messages in the buffer. In my experience, that usually causes the application to crash. Since I'd rather lose a few INFO/DEBUG/TRACE messages (but not WARN and ERROR), I set the queue full policy to DISCARD at a threshold of INFO.

**Comment by madmessmoving** [comment]
Thanks for the detailed info. I'll try these out and check with MS about possibility of dropping the jar file on cloudhub. I'll update you on what comes out. Thanks again!
